### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by Sousxs** [xabbo/xabbo#13]
How can I fix this error? I’ve tried restarting multiple times, but it didn’t solve the issue. I installed .NET twice times.

xabbo v1.1.3
''
Unresolved identifiers (Incoming: f:FurniListInvalidate, FurniList, f:FurniListAddOrUpdate, f:FurniListRemove)
   at Xabbo.Messages.MessageDispatcher.Attach(InterceptGroup group) in Xabbo.Common/Messages/MessageDispatcher.cs:line 231
   at Xabbo.Messages.MessageDispatcher.Register(InterceptGroup group) in Xabbo.Common/Messages/MessageDispatcher.cs:line 164
   at Xabbo.Core.Game.InventoryManager.global::Xabbo.Messages.IMessageHandler.Attach(IInterceptor interceptor) in Xabbo.Core/Xabbo.Common.Generator/Xabbo.Common.Generator.Generator/Xabbo.Core.Game.InventoryManager.Interceptor.g.cs:line 7
   at Xabbo.Core.Game.GameStateManager.OnConnected(ConnectedEventArgs e) in Xabbo.Core/Game/GameStateManager.cs:line 56
   at Xabbo.GEarth.GEarthExtension.OnConnected(ConnectedEventArgs e) in Xabbo.GEarth/GEarthExtension.cs:line 119
   at Xabbo.GEarth.GEarthExtension.HandleConnectionStart(Packet packet) in Xabbo.GEarth/GEarthExtension.cs:line 694
   at Xabbo.GEarth.GEarthExtension.HandlePacket(Packet packet) in Xabbo.GEarth/GEarthExtension.cs:line 459
   at Xabbo.GEarth.GEarthExtension.ProcessPipeAsync(PipeReader reader, CancellationToken cancellationToken) in Xabbo.GEarth/GEarthExtension.cs:line 384
   at Xabbo.GEarth.GEarthExtension.HandleInterceptorAsync(GEarthConnectOptions connectOpts, CancellationToken cancellationToken) in Xabbo.GEarth/GEarthExtension.cs:line 304
   at Xabbo.GEarth.GEarthExtension.RunAsync(GEarthConnectOptions connectOpts, CancellationToken cancellationToken) in Xabbo.GEarth/GEarthExtension.cs:line 225
   at Xabbo.Avalonia.Services.XabboAppManager.RunExtensionAsync()
'''

**Comment by b7c** [comment]
The Sulek API was missing some packet headers, Mikee has fixed the issue. Delete the G-Earth/Cache folder and restart G-Earth, it should fetch the updated headers.
