### ISSUE TITLE
Format error

### ISSUE THREAD

**Issue by Larpss** [xabbo/xabbo#9]
Hi, I'm getting this error when trying to execute the extension:

```
xabbo v1.1.0

Session details:
  Hotel: Brazil
  Client type: Flash
  Client identifier: FLASH19
  Client version: WIN63-202405301104-303662002

Message details:
  Direction: In
  Header value: 3645
  Name: CreditBalance

The input string '0.0' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Single.Parse(String s)
   at Xabbo.FloatString.op_Explicit(String value) in Xabbo.Common/FloatString.cs:line 18
   at Xabbo.Core.Messages.Incoming.CreditBalanceMsg.Xabbo.Messages.IParser<Xabbo.Core.Messages.Incoming.CreditBalanceMsg>.Parse(PacketReader& p) in Xabbo.Core/Messages/Incoming/CreditBalanceMsg.cs:line 24
   at Xabbo.Intercept`1.get_Msg() in Xabbo.Common/Intercept{TMsg}.cs:line 30
   at Xabbo.Core.Game.ProfileManager.HandleCreditBalance(Intercept`1 e) in Xabbo.Core/Game/Profile/ProfileManager.Handlers.cs:line 83
   at Xabbo.Messages.IMessage`1.<>c__DisplayClass11_0.<CreateHandler>b__0(Intercept e) in Xabbo.Common/Messages/IMessage{TMsg}.cs:line 59
   at Xabbo.Messages.MessageDispatcher.Dispatch(List`1 list, Intercept intercept) in Xabbo.Common/Messages/MessageDispatcher.cs:line 86
  ```
   
 I tried to troubleshoot and found out that error occours because my Regional Format (Portuguese - Portugal) uses comma instead of period in decimals.

**Comment by b7c** [comment]
Hi thanks for reporting this, I will release a fix shortly
